app/__init__.py
from flask import Flask
from flask_mail import Mail

from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_pymongo import PyMongo

from config import config

mail = Mail()

mongo = PyMongo()

login_manager = LoginManager()
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    # flask ext init
    mail.init_app(app)  # read app.config to mail
    login_manager.init_app(app)
    bootstrap.init_app(app)

    mongo.init_app(app)

    # init routes
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from .api_1_0 import api as api_1_0_blueprint
    app.register_blueprint(api_1_0_blueprint, url_prefix='/api/v1.0')
    return app

app/api_1_0/__init__.py
from flask import Blueprint

api = Blueprint('from . import authentication, posts, users, comments, errorsapi', __name__)
from . import  errors

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes, errors

app/main/routes.py
from flask import render_template, redirect, url_for
from . import main

from flask_login import LoginManager, login_required
# from app.auth.my_auth_decorators import login_required


@main.route('/dashboard', methods=['GET'])
@login_required
def dashboard():
    return render_template('dashboard.html', title="Home")


@main.route('/', methods=['GET', 'POST'])
def index():
    return render_template('index.html', title="Home")

app/templates/_api_client.html
{% if current_user.is_authenticated() %}
<script>
    var talks_api_token = "{{ current_user.get_api_token() | safe }}";
    function talks_api(url, method, data, success, error) {
        if (!data)
            data = {}
        data.token = talks_api_token;
        req_url = location.protocol + '//' + location.host + '/api/1.0' + url
        $.ajax({
            url: req_url,
            type: method,
            data: JSON.stringify(data),
            contentType: 'application/json',
            success: success,
            error: error
        });
    }
    $('.api-approve').click(function() {
        id = $(this).data('id');
        url = location.protocol + '//' + location.host + '/api/1.0/comments/' + id
        talks_api('/comments/' + id, 'PUT', {}, function() {
            $('#moderate-' + id).hide();
            $('#approved-' + id).show();
        },
        function(jqXHR, textStatus, errorThrown) {
            alert('Error: ' + errorThrown);
        });
        return false;
    });
    $('.api-delete').click(function() {
        id = $(this).data('id');
        url = location.protocol + '//' + location.host + '/api/1.0/comments/' + id
        talks_api('/comments/' + id, 'DELETE', {}, function() {
            $('#moderate-' + id).hide();
            $('#deleted-' + id).show();
        },
        function(jqXHR, textStatus, errorThrown) {
            alert('Error: ' + errorThrown);
        });
        return false;
    });
</script>
{% endif %}

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Flask+Mongo - {{ title }}{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/flask.png') }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
    {% block head %}

    {% endblock %}
</head>
<body>
{% block navbar %}
{% endblock %}

{% block content %}
    {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
{% endblock %}

{% block footer %}
{% endblock %}

{% block scripts %}

{% endblock %}
</body>
</html>

app/templates/base_bs.html
{% extends "bootstrap/base.html" %}

{% block title %}Flask+Mongo - {{ title }}{% endblock %}

{% block head %}
{{ super() }}
<link rel="icon" href="{{ url_for('static', filename='images/flask.png') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}
    {% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/base_bs_nav.html
{% extends "base_bs.html" %}
{% block title %}Flask+Mongo {{ title }}{% endblock %}


{% block navbar %}
{% include 'nav.html' %}
{% endblock %}

app/templates/dashboard.html
{% extends "base_bs_nav.html" %}

{% block page_content %}
    <h1>Hello, {{ current_user.username }}!</h1>
{#    <base href ="/">#}
{#    <my-app><!-- content managed by Angular --></my-app>#}
{% endblock %}

{% block scripts %}
{{ super() }}
    <script type="text/javascript" src="static/js_app/inline.bundle.js"></script>
    <script type="text/javascript" src="static/js_app/polyfills.bundle.js"></script>
    <script type="text/javascript" src="static/js_app/vendor.bundle.js"></script>
    <script type="text/javascript" src="static/js_app/main.bundle.js"></script>
{% endblock %}

app/templates/dashborad.html
{% extends "base.html" %}

{% block page_content %}
    <base href ="/">
    <my-app><!-- content managed by Angular --></my-app>
{% endblock %}

{% block scripts %}
{{ super() }}
    <script type="text/javascript" src="static/js_app/inline.bundle.js"></script>
    <script type="text/javascript" src="static/js_app/polyfills.bundle.js"></script>
    <script type="text/javascript" src="static/js_app/vendor.bundle.js"></script>
    <script type="text/javascript" src="static/js_app/main.bundle.js"></script>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}


{% block page_content %}
    <h1>Welcome</h1>
    <a href="{{ url_for('.dashboard') }}">Go to dashboard</a>
{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}

app/templates/nav.html
<div class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Flask+Mongo</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.dashboard') }}">Dashboard</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="">
                            Account <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                            <li><a href="{{ url_for('auth.login') }}">Switch Account</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

app/templates/talks/_comment.html
<p>
    {% if comment.author %}
        {% if index %}
        <span class="label label-primary">#{{ index }}</span>
        {% endif %}
        <a href="{{ url_for('.user', username=comment.author.username) }}">{{ comment.author.username }}</a>
    {% else %}
        {% if talk.author == current_user or current_user.is_admin %}
            {% if not comment.approved %}
            <div id="moderate-{{ comment.id }}" class="pull-right">
                <a class="btn btn-primary api-approve" data-id="{{ comment.id }}" href="#"><span class="glyphicon glyphicon-ok"></span> Approve</a>
                <a class="btn btn-danger api-delete" data-id="{{ comment.id }}" href="#"><span class="glyphicon glyphicon-trash"></span> Delete</a>
            </div>
            <div id="approved-{{ comment.id }}" class="pull-right" style="display: none;">
                <span class="glyphicon glyphicon-ok"></span> <b>Approved</b>
            </div>
            <div id="deleted-{{ comment.id }}" class="pull-right" style="display: none;">
                <span class="glyphicon glyphicon-trash"></span> <b>Deleted</b>
            </div>
            {% endif %}
        {% endif %}
        {% if index %}
        <span class="label label-default">#{{ index }}</span>
        {% endif %}
        <b>{{ comment.author_name }}</b>
        {% if current_user.is_authenticated() and (talk.author == current_user or current_user.is_admin) %}
        (<a href="mailto:{{ comment.author_email }}">{{ comment.author_email }}</a>)
        {% endif %}
    {% endif %}
    commented {{ moment(comment.timestamp).fromNow() }}:
</p>
<div class="comment-body">
    {{ comment.body_html | safe }}
</div>

app/templates/talks/_comments.html
<ul class="comment-list">
{% if pagination %}
    {% set base_index = (pagination.page - 1) * pagination.per_page %}
{% else %}
    {% set base_index = 0 %}
{% endif %}
{% for comment in comments %}
    {% set index = loop.index + base_index %}
    <li class="comment">
        {% include "talks/_comment.html" %}
    </li>
{% endfor %}
</ul>

app/templates/talks/_talk_header.html
<div class="talk-header">
    {% if talk.author == current_user %}
    <a class="btn btn-primary pull-right" href="{{ url_for('talks.edit_talk', id=talk.id) }}">Edit</a>
    {% elif current_user.is_admin %}
    <a class="btn btn-danger pull-right" href="{{ url_for('talks.edit_talk', id=talk.id) }}">Edit</a>
    {% endif %}
    <h2><a href="{{ url_for('talks.talk', id=talk.id) }}">{{ talk.title }}</a></h2>
    <h3>{{ talk.description }}</h3>
    <div class="pull-right"><a href="{{ url_for('talks.talk', id=talk.id) }}#comments"><span class="label label-default">Comments: {{ talk.approved_comments().count() }}</span></a></div>
    <p>
        Presented by <a href="{{ url_for('talks.user', username=talk.author.username) }}">{{ talk.author.username }}</a> at
        {% if talk.venue_url %}
            <a href="{{ talk.venue_url }}">{{ talk.venue }}</a>
        {% else %}
            {{ talk.venue }}
        {% endif %}
        on {{ moment(talk.date, local=True).format('LL') }}.
    </p>
</div>

app/templates/talks/_talks.html
<ul class="talk-list">
{% for talk in talks %}
    <li class="talk">
    {% include "talks/_talk_header.html" %}
    </li>
{% endfor %}
</ul>

app/templates/talks/edit_talk.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>Talk</h1>
</div>
{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/talks/index.html
{% extends "base.html" %}

{% block page_content %}
{% include "talks/_talks.html" %}
{% if talks %}
<ul class="pager">
    {% if pagination.has_prev %}
    <li class="previous"><a href="{{ url_for('talks.index', page=pagination.prev_num) }}">&larr; Newer</a></li>
    {% else %}
    <li class="previous disabled"><a href="#">&larr; Newer</a></li>
    {% endif %}
    {% if pagination.has_next %}
    <li class="next"><a href="{{ url_for('talks.index', page=pagination.next_num) }}">Older &rarr;</a></li>
    {% else %}
    <li class="next disabled"><a href="#">Older &rarr;</a></li>
    {% endif %}
</ul>
{% endif %}
{% endblock %}

app/templates/talks/moderate.html
{% extends "base.html" %}

{% block page_content %}
<h2>Comment moderation</h2>
<ul class="comment-list">
{% for comment in comments %}
    {% set talk = comment.talk %}
    <li class="comment">
        <p>In <a href="{{ url_for('talks.talk', id=talk.id) }}">{{ talk.title }}</a></p>
        {% include "talks/_comment.html" %}
    </li>
{% endfor %}
</ul>
{% endblock %}

{% block scripts %}
{{ super() }}
{% include "_api_client.html" %}
{% endblock %}

app/templates/talks/profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Profile</h1>
</div>
{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/talks/talk.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    {% include "talks/_talk_header.html" %}
</div>
<div class="talk-body">
    {% if talk.video %}
    <div class="talk-video">
    {{ talk.video | safe }}
    </div>
    {% endif %}
    {% if talk.slides %}
    <div class="talk-slides">
    {{ talk.slides | safe }}
    </div>
    {% endif %}
</div>
{% if comments %}
<h3 id="comments">Comments</h3>
{% include "talks/_comments.html" %}
<ul class="pager">
    {% if pagination.has_prev %}
    <li class="previous"><a href="{{ url_for('talks.talk', id=talk.id, page=pagination.prev_num) }}#comments">&larr; Older</a></li>
    {% else %}
    <li class="previous disabled"><a href="#">&larr; Older</a></li>
    {% endif %}
    {% if pagination.has_next %}
    <li class="next"><a href="{{ url_for('talks.talk', id=talk.id, page=pagination.next_num) }}#comments">Newer &rarr;</a></li>
    {% else %}
    <li class="next disabled"><a href="#">Newer &rarr;</a></li>
    {% endif %}
</ul>
{% endif %}
<h3 id="comment-form">Write a comment</h3>
{{ wtf.quick_form(form, action='#comment-form') }}
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
<script src="http://cdnjs.cloudflare.com/ajax/libs/autosize.js/1.18.1/jquery.autosize.min.js"></script>
<script>
    $(document).ready(function() {
        $('#flask-pagedown-body').autosize();
    });
</script>
{% include "_api_client.html" %}
{% endblock %}

app/templates/talks/user.html
{% extends "base.html" %}

{% block page_content %}
<div class="page-header user-profile">
    <div class="user-avatar"><img src="{{ user.gravatar(128) }}"></div>
    {% if current_user == user %}<a class="btn btn-default pull-right" href="{{ url_for('talks.profile') }}">Edit Profile</a>{% endif %}
    <h1>{{ user.username }}</h1>
    <p>
        {% if user.name %}{{ user.name }}<br>{% endif %}
        {% if user.location %}<a href="http://maps.google.com?q={{ user.location }}">{{ user.location }}</a><br>{% endif %}
    </p>
    {% if user.bio %}<p>{{ user.bio }}</p>{% endif %}
</div>
{% include "talks/_talks.html" %}
{% if talks %}
<ul class="pager">
    {% if pagination.has_prev %}
    <li class="previous"><a href="{{ url_for('talks.user', username=user.username, page=pagination.prev_num) }}">&larr; Newer</a></li>
    {% else %}
    <li class="previous disabled"><a href="#">&larr; Newer</a></li>
    {% endif %}
    {% if pagination.has_next %}
    <li class="next"><a href="{{ url_for('talks.user', username=user.username, page=pagination.next_num) }}">Older &rarr;</a></li>
    {% else %}
    <li class="next disabled"><a href="#">Older &rarr;</a></li>
    {% endif %}
</ul>
{% endif %}
{% endblock %}